//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data50
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gpvEntities50 : DbContext
    {
        public gpvEntities50()
            : base("name=gpvEntities50")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<claudiaTesteEntity> claudiaTesteEntities { get; set; }
        public DbSet<martiniTesteEntity> martiniTesteEntities { get; set; }
        public DbSet<tFatTarefaEntity> tFatTarefaEntities { get; set; }
        public DbSet<tSegFuncionalidadeEntity> tSegFuncionalidadeEntities { get; set; }
        public DbSet<tSegPerfilEntity> tSegPerfilEntities { get; set; }
        public DbSet<tSegPerfilTelaFuncionalidadeEntity> tSegPerfilTelaFuncionalidadeEntities { get; set; }
        public DbSet<tSegTelaEntity> tSegTelaEntities { get; set; }
        public DbSet<tSegTelaFuncionalidadeEntity> tSegTelaFuncionalidadeEntities { get; set; }
        public DbSet<tSegUsuarioEntity> tSegUsuarioEntities { get; set; }
    }
}
