//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data50
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFatTarefaEntity
    {
        public int UID_TAREFA { get; set; }
        public int COD_PAIS { get; set; }
        public string USUARIO_ULTIMA_ALTERACAO { get; set; }
        public Nullable<System.DateTime> data_finalizacao { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public string NOME_TAREFA { get; set; }
    }
}
