//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data50
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSegTelaFuncionalidadeEntity
    {
        public tSegTelaFuncionalidadeEntity()
        {
            this.tSegPerfilTelaFuncionalidades = new HashSet<tSegPerfilTelaFuncionalidadeEntity>();
        }
    
        public int UID_TELA_FUNC { get; set; }
        public string TELA_FUNC_DESCRICAO { get; set; }
        public int UID_FUNCIONALIDADE { get; set; }
        public int UID_TELA { get; set; }
    
        public virtual tSegFuncionalidadeEntity tSegFuncionalidade { get; set; }
        public virtual ICollection<tSegPerfilTelaFuncionalidadeEntity> tSegPerfilTelaFuncionalidades { get; set; }
        public virtual tSegTelaEntity tSegTela { get; set; }
    }
}
