//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data50
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSegPerfilTelaFuncionalidadeEntity
    {
        public int UID_PERFIL_TELA_FUNC { get; set; }
        public int COD_PAIS { get; set; }
        public int UID_PERFIL { get; set; }
        public int UID_TELA_FUNC { get; set; }
    
        public virtual tSegPerfilEntity tSegPerfil { get; set; }
        public virtual tSegTelaFuncionalidadeEntity tSegTelaFuncionalidade { get; set; }
    }
}
