//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data50
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSegPerfilEntity
    {
        public tSegPerfilEntity()
        {
            this.tSegPerfilTelaFuncionalidades = new HashSet<tSegPerfilTelaFuncionalidadeEntity>();
            this.tSegUsuarios = new HashSet<tSegUsuarioEntity>();
        }
    
        public int UID_PERFIL { get; set; }
        public string PER_DES { get; set; }
    
        public virtual ICollection<tSegPerfilTelaFuncionalidadeEntity> tSegPerfilTelaFuncionalidades { get; set; }
        public virtual ICollection<tSegUsuarioEntity> tSegUsuarios { get; set; }
    }
}
