//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data6x
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSegUsuarioEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSegUsuarioEntity()
        {
            this.tSegPerfils = new HashSet<tSegPerfilEntity>();
        }
    
        public int UID_USUARIO { get; set; }
        public int COD_PAIS { get; set; }
        public bool USU_FLG_ATIVO { get; set; }
        public string USU_DES_LOCALE { get; set; }
        public string USU_NOM_LOGIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSegPerfilEntity> tSegPerfils { get; set; }
    }
}
