//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPattern.WProject.Data6x
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSegFuncionalidadeEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSegFuncionalidadeEntity()
        {
            this.tSegTelaFuncionalidades = new HashSet<tSegTelaFuncionalidadeEntity>();
        }
    
        public int UID_FUNCIONALIDADE { get; set; }
        public string FUN_CHAVE { get; set; }
        public string FUN_DES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSegTelaFuncionalidadeEntity> tSegTelaFuncionalidades { get; set; }
    }
}
